# Generated by Django 2.2.4 on 2020-11-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonvoyage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='action_taken',
            field=models.BooleanField(default=False),
        ),
    ]
