# Generated by Django 2.2.4 on 2020-11-15 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfavoritevacation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='users.Customer'),
        ),
        migrations.AlterField(
            model_name='customerfavoritevacation',
            name='vacation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='vacations.Vacation'),
        ),
    ]
