# Generated by Django 2.2 on 2020-10-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerfavoritevacation',
            unique_together={('customer', 'trip')},
        ),
    ]
