# Generated by Django 2.2 on 2020-10-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201024_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='preferred_type_of_vacations',
        ),
    ]
