# Generated by Django 2.2.16 on 2020-10-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Vacation name')),
                ('destination', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('destination_image', models.ImageField(upload_to='photos')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Trip name')),
                ('source', models.CharField(max_length=60, verbose_name='Starting point')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('mode_of_transport', models.CharField(choices=[('FL', 'Flight'), ('TR', 'Train'), ('CR', 'Cruise'), ('BU', 'Bus')], max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price ($)')),
                ('additional_benefits', models.CharField(max_length=200)),
                ('trip_description', models.TextField()),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vacations.Vacation')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
